### ISSUE TITLE
Uninformative error message

### ISSUE THREAD

**Issue by matthewdeanmartin** [dave-shawley/setupext-gitversion#9]
I'm not following from the README nor the error message how the git repo must be prepped before using this.

```
± |master ✓| → python setup.py git_version sdist
running git_version
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    'git_version': gitversion.GitVersion,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/martinmat/.virtualenvs/ver_test1/lib/python3.6/site-packages/setupext/gitversion.py", line 39, in run
    '{0}...HEAD'.format(starting_rev))
  File "/Users/martinmat/.virtualenvs/ver_test1/lib/python3.6/site-packages/setupext/gitversion.py", line 81, in _run_git
    stdout, stderr = _run_command('git', *args)
  File "/Users/martinmat/.virtualenvs/ver_test1/lib/python3.6/site-packages/setupext/gitversion.py", line 99, in _run_command
    ' '.join(exec_list))
subprocess.CalledProcessError: Command 'git rev-list --merges 1.2.31.1.3...HEAD' returned non-zero exit status 128.
```

**Comment by andrewrabert** [comment]
This occurs when there is no git tag corresponding to the package version. In your situation, there probably wasn't a tag for `1.2.31.1.3`.

@dave-shawley Wondering if it's sane to use the `pre` identifier when this happens.
https://www.python.org/dev/peps/pep-0440/#pre-release-spelling
